server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://cloud:5432/tweet-service
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: cloud
      port: 6379
#  kafka:
#    bootstrap-servers: cloud:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

springdoc:
  api-docs:
    path: /tweet-service/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://cloud:9411/api/v2/spans
  
services:
  profile:
    name: profile-service
  storage:
    name: storage-service
